edureka@kmaster:~$ cd /home/dockeradmin
edureka@kmaster:/home/dockeradmin$ ls -lrth
total 6.9M 
-rwxrwxrwx 1 dockeradmin dockeradmin  228 Feb  8 20:44 Dockerfile
-rwxrwxrwx 1 dockeradmin dockeradmin   13 Feb  8 21:27 hosts
-rwxrwxrwx 1 dockeradmin dockeradmin  879 Feb  8 22:00 create_image_run_container_push2repo.yml
-rwxrwxrwx 1 dockeradmin dockeradmin 1.0K Feb  8 22:08 create_deployment_service.yml
-rwxrwxrwx 1 dockeradmin dockeradmin  533 Feb  8 23:08 kube_deploy.yml
-rwxrwxrwx 1 dockeradmin dockeradmin  245 Feb  8 23:29 kube_service.yml
-rwxrwxrwx 1 dockeradmin dockeradmin 6.9M Feb 20 07:43 ABCtechnologies-1.0.war
edureka@kmaster:/home/dockeradmin$ cat kube_deploy.yml
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: edureka-deployment
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: edureka-devops-project

  template:
    metadata:
      labels:
        app: edureka-devops-project
    spec:
      containers:
      - name: edureka-devops-project
        image: vermakeshav1994/abctechnologies_kubernetes
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
edureka@kmaster:/home/dockeradmin$ 
